# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['popularity_resonance_gui.py'],
    pathex=[],
    binaries=[],
    datas=[("JohnsonUtil/global.ini", "JohnsonUtil"),],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'talib',
        'h5py',
        'tables',
        'PyQt5',
        'PyQt6',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'django',
        'flask',
        'fastapi',
        'uvicorn',
        'notebook',
        'jupyter',
        'IPython',
        'wcwidth',
        'jedi',
        'tornado',
        'nbformat',
        'nbconvert',
        'lxml',
        'cryptography',
        'argon2',
        'bcrypt',
        'nacl',
        'zmq',
        'sqlalchemy',
        'openpyxl',
        'numba',
        'llvmlite',
        'PIL',
        'shiboken6',
        'qtpy',
        'talib.stream',
        'talib.abstract',
        'sys_performance_analyzer'
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='人气共振2.22',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
